### PR TITLE
Add type 'datetimeoffset' to type mappings in the README.md.

### PR DESCRIPTION
**Pull request by fpauser**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shdblowers** [comment]
Hello, @fpauser! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/findmypast-oss/mssql_ecto/pulls/11). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by shdblowers** [comment]
Hi @fpauser I could not find this Ecto type in the official documentation, do you have a link?

**Comment by fpauser** [comment]
Hi @shdblowers, you are right. As it looks support for datetimeoffset must be added to `mssqlex`.

**Comment by shdblowers** [comment]
I meant that I could not find it in the Ecto documentation.

**Pull request closed without merging**
